name: lint
on: [pull_request, push]
jobs:
  prek:
    runs-on: ubuntu-latest
    env:
      PREK_COLOR: always
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.x'
      - name: Set up prek
        uses: j178/prek-action@564dda4cfa5e96aafdc4a5696c4bf7b46baae5ac # v1.1.0
        with:
          install-only: true
      - name: Run gitlint
        run: prek run --hook-stage manual gitlint-ci
      - name: Run prek
        run: prek run --all-files --show-diff-on-failure
